import { Link } from '@inertiajs/react';
import {
    ClipboardList,
    Database,
    Dna,
    Image,
    Info,
    LayoutGrid,
    Network,
    Newspaper,
    Users,
} from 'lucide-react';
import AppLogo from '@/components/app-logo';
import { NavMain } from '@/components/nav-main';
import { NavUser } from '@/components/nav-user';
import {
    Sidebar,
    SidebarContent,
    SidebarFooter,
    SidebarHeader,
    SidebarMenu,
    SidebarMenuButton,
    SidebarMenuItem,
} from '@/components/ui/sidebar';
import admin from '@/routes/admin';
import type { NavItem } from '@/types';

/**
 * Admin module navigation (Req 9.4): the sidebar surfaces every management
 * module so an authenticated admin can reach all CRUD areas. Links resolve to
 * the `admin.*` named routes generated by Wayfinder, all guarded by the
 * `['auth', 'admin']` middleware group (Req 9.3).
 */
const mainNavItems: NavItem[] = [
    {
        title: 'Dashboard',
        href: admin.dashboard(),
        icon: LayoutGrid,
    },
    {
        title: 'Artikel',
        href: admin.artikel.index(),
        icon: Newspaper,
    },
    {
        title: 'Tentang',
        href: admin.tentang.edit(),
        icon: Info,
    },
    {
        title: 'Ilustrasi',
        href: '/admin/media',
        icon: Image,
    },
    {
        title: 'Basis Pengetahuan',
        href: '/admin/basis-pengetahuan',
        icon: Network,
    },
    {
        title: 'Fenotipe',
        href: admin.fenotipe.index(),
        icon: Dna,
    },
    {
        title: 'Data Latih',
        href: admin.dataLatih.index(),
        icon: Database,
    },
    {
        title: 'Hasil Prediksi',
        href: admin.hasilPrediksi.index(),
        icon: ClipboardList,
    },
    {
        title: 'Pengguna',
        href: '/admin/pengguna',
        icon: Users,
    },
];

export function AppSidebar() {
    return (
        <Sidebar collapsible="icon" variant="inset">
            <SidebarHeader>
                <SidebarMenu>
                    <SidebarMenuItem>
                        <SidebarMenuButton size="lg" asChild>
                            <Link href={admin.dashboard()} prefetch>
                                <AppLogo />
                            </Link>
                        </SidebarMenuButton>
                    </SidebarMenuItem>
                </SidebarMenu>
            </SidebarHeader>

            <SidebarContent>
                <NavMain items={mainNavItems} />
            </SidebarContent>

            <SidebarFooter>
                <NavUser />
            </SidebarFooter>
        </Sidebar>
    );
}
